### ISSUE TITLE
Allow defining groups of packages to install

### ISSUE THREAD

**Issue by jhorzek** [Factworks/factverse#6]
Factverse can install all packages outlined in the package_list project. Currently, factverse only allows for two different elements in these package lists:

- packages: a list with the names of all available packages
- essentials: a list with the names of all essential packages

It would be nice to have a more dynamic approach, where we can define custom elements (e.g., a list for driver modeling or a list for descriptives). Also, we could remove the "packages" list and just enforce that every new package must always be added to one/multiple of the more specific lists

- [ ] Add a function called install_package_group that gets all packages in a specific list from a specific account. This would be similar to the [install_essentials](https://github.com/Factworks/factverse/blob/a86c63458817aab617adbe6287c8cbedad55edee/R/install_packages.R#L254) function, but more general. The function call should be install_package_group(account = NULL, package_group)
- [ ] Update the [install_essentials](https://github.com/Factworks/factverse/blob/a86c63458817aab617adbe6287c8cbedad55edee/R/install_packages.R#L254)
 function to call the install_package_group
- [ ] Rework the package so that we do not need to have a list "packages" that outlines all available packages. Currently, this list is used in multiple slots (e.g., [here](https://github.com/Factworks/factverse/blob/a86c63458817aab617adbe6287c8cbedad55edee/R/install_packages.R#L66)). A simple workaround would be to automatically add a field all_packages when retrieving the packages with get_available_packages.

**Comment by cmbosancianu** [comment]
Based on a suggestion from @jhorzek as well, a possible way to do this is to structure the `package_list.yaml` document in a hierarchical way (tentative proposal below).

```
---
packages:
    - factworks: [dep_package_1, dep_package_2]
    - catchr: [dep_package_1, dep_package_3]
    - package_4
    - ...
groups:
    - essentials: [factworks]
    - segmentation: [package_4, package_5, catchr]
    - conjoints: [package_5, package_6]
```

`dep_package_1` and the others starting with `dep_` denote dependencies to other FW packages (connected to issue #13 ). To work well, this would require that a package be listed in its own slot in `packages` before being added to a slot in `groups` (since installing a package group would require matching package names in that group to slots in `packages` so as to retrieve dependencies).
